{"uid":"d6847f380a590f14","name":"test_earn","fullName":"test_case.test_balance_wallete_scenario_.TestScenario#test_earn","historyId":"45a021e7df45e6c7cfbe9d9f421fd9cb","time":{"start":1728656039290,"stop":1728656043912,"duration":4622},"status":"broken","statusMessage":"selenium.common.exceptions.StaleElementReferenceException: Message: The previously found element \"\"chevron-down\" Image\" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(\n    Image, {{134.7, 201.0}, {20.0, 20.0}}, label: 'chevron-down'\n)}; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\nStaleElementReferenceError: The previously found element \"\"chevron-down\" Image\" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(\n    Image, {{134.7, 201.0}, {20.0, 20.0}}, label: 'chevron-down'\n)}\n    at errorFromW3CJsonCode (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)\n    at ProxyRequestError.getActualError (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)\n    at JWProxy.proxyReqRes (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:410:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","statusTrace":"self = <test_balance_wallete_scenario_.TestScenario object at 0x106a16970>\n\n    def test_earn(self):\n        self.common_page.click_element(self.earn_page.bottom_tab_earn_button())\n        self.common_page.click_element(self.earn_page.earn_way_to_no_button())\n    \n>       self.earn_page.set_default_first_network()\n\ntest_case/test_balance_wallete_scenario_.py:81: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage/earn_page.py:103: in set_default_first_network\n    self.common_page.click_element(\"chevron-down\")\npage/common_page.py:50: in click_element\n    self.interaction_handler.click_on(locator)\npage/element_interaction_handle.py:20: in click_on\n    element = WebDriverWait(self.driver, wait_time).until(\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:96: in until\n    value = method(self._driver)\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:364: in _predicate\n    element = visibility_of(target)(driver)\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:173: in _predicate\n    return _element_if_visible(element)\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:179: in _element_if_visible\n    return element if element.is_displayed() == visibility else False\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/appium/webdriver/webelement.py:80: in is_displayed\n    return self._execute(Command.IS_ELEMENT_DISPLAYED)['value']\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py:395: in _execute\n    return self._parent.execute(command, params)\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x106ae6a60>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"The previously found element \\\\\"\\\\\"ch...ver/lib/jsonwp-proxy/proxy.js:410:58)\\\\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"\n        https://www.w3.org/TR/webdriver/#errors\n        \"\"\"\n        payload = response.get('value', '')\n        if isinstance(payload, dict):\n            payload_dict = payload\n        else:\n            try:\n                payload_dict = json.loads(payload)\n            except (json.JSONDecodeError, TypeError):\n                return\n            if not isinstance(payload_dict, dict):\n                return\n        value = payload_dict.get('value')\n        if not isinstance(value, dict):\n            return\n        error = value.get('error')\n        if not error:\n            return\n    \n        message = value.get('message', error)\n        stacktrace = value.get('stacktrace', '')\n        # In theory, we should also be checking HTTP status codes.\n        # Java client, for example, prints a warning if the actual `error`\n        # value does not match to the response's HTTP status code.\n        exception_class: Type[sel_exceptions.WebDriverException] = ERROR_TO_EXC_MAPPING.get(\n            error, sel_exceptions.WebDriverException\n        )\n        if exception_class is sel_exceptions.WebDriverException and message:\n            if message == 'No such context found.':\n                exception_class = appium_exceptions.NoSuchContextException\n            elif message == 'That command could not be executed in the current context.':\n                exception_class = appium_exceptions.InvalidSwitchToTargetException\n    \n        if exception_class is sel_exceptions.UnexpectedAlertPresentException:\n            raise sel_exceptions.UnexpectedAlertPresentException(\n                msg=message,\n                stacktrace=format_stacktrace(stacktrace),\n                alert_text=value.get('data'),\n            )\n>       raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\nE       selenium.common.exceptions.StaleElementReferenceException: Message: The previously found element \"\"chevron-down\" Image\" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(\nE           Image, {{134.7, 201.0}, {20.0, 20.0}}, label: 'chevron-down'\nE       )}; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       StaleElementReferenceError: The previously found element \"\"chevron-down\" Image\" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(\nE           Image, {{134.7, 201.0}, {20.0, 20.0}}, label: 'chevron-down'\nE       )}\nE           at errorFromW3CJsonCode (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)\nE           at ProxyRequestError.getActualError (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)\nE           at JWProxy.proxyReqRes (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:410:58)\nE           at processTicksAndRejections (node:internal/process/task_queues:105:5)\n\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/appium/webdriver/errorhandler.py:125: StaleElementReferenceException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[{"name":"os_type","time":{"start":1728655959633,"stop":1728655959633,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"appium_server","time":{"start":1728655959634,"stop":1728655971672,"duration":12038},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"driver","time":{"start":1728656036343,"stop":1728656037772,"duration":1429},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"setup","time":{"start":1728656037772,"stop":1728656039289,"duration":1517},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false}],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.StaleElementReferenceException: Message: The previously found element \"\"chevron-down\" Image\" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(\n    Image, {{134.7, 201.0}, {20.0, 20.0}}, label: 'chevron-down'\n)}; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\nStaleElementReferenceError: The previously found element \"\"chevron-down\" Image\" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(\n    Image, {{134.7, 201.0}, {20.0, 20.0}}, label: 'chevron-down'\n)}\n    at errorFromW3CJsonCode (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)\n    at ProxyRequestError.getActualError (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)\n    at JWProxy.proxyReqRes (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:410:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","statusTrace":"self = <test_balance_wallete_scenario_.TestScenario object at 0x106a16970>\n\n    def test_earn(self):\n        self.common_page.click_element(self.earn_page.bottom_tab_earn_button())\n        self.common_page.click_element(self.earn_page.earn_way_to_no_button())\n    \n>       self.earn_page.set_default_first_network()\n\ntest_case/test_balance_wallete_scenario_.py:81: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage/earn_page.py:103: in set_default_first_network\n    self.common_page.click_element(\"chevron-down\")\npage/common_page.py:50: in click_element\n    self.interaction_handler.click_on(locator)\npage/element_interaction_handle.py:20: in click_on\n    element = WebDriverWait(self.driver, wait_time).until(\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:96: in until\n    value = method(self._driver)\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:364: in _predicate\n    element = visibility_of(target)(driver)\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:173: in _predicate\n    return _element_if_visible(element)\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:179: in _element_if_visible\n    return element if element.is_displayed() == visibility else False\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/appium/webdriver/webelement.py:80: in is_displayed\n    return self._execute(Command.IS_ELEMENT_DISPLAYED)['value']\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py:395: in _execute\n    return self._parent.execute(command, params)\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x106ae6a60>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"The previously found element \\\\\"\\\\\"ch...ver/lib/jsonwp-proxy/proxy.js:410:58)\\\\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"\n        https://www.w3.org/TR/webdriver/#errors\n        \"\"\"\n        payload = response.get('value', '')\n        if isinstance(payload, dict):\n            payload_dict = payload\n        else:\n            try:\n                payload_dict = json.loads(payload)\n            except (json.JSONDecodeError, TypeError):\n                return\n            if not isinstance(payload_dict, dict):\n                return\n        value = payload_dict.get('value')\n        if not isinstance(value, dict):\n            return\n        error = value.get('error')\n        if not error:\n            return\n    \n        message = value.get('message', error)\n        stacktrace = value.get('stacktrace', '')\n        # In theory, we should also be checking HTTP status codes.\n        # Java client, for example, prints a warning if the actual `error`\n        # value does not match to the response's HTTP status code.\n        exception_class: Type[sel_exceptions.WebDriverException] = ERROR_TO_EXC_MAPPING.get(\n            error, sel_exceptions.WebDriverException\n        )\n        if exception_class is sel_exceptions.WebDriverException and message:\n            if message == 'No such context found.':\n                exception_class = appium_exceptions.NoSuchContextException\n            elif message == 'That command could not be executed in the current context.':\n                exception_class = appium_exceptions.InvalidSwitchToTargetException\n    \n        if exception_class is sel_exceptions.UnexpectedAlertPresentException:\n            raise sel_exceptions.UnexpectedAlertPresentException(\n                msg=message,\n                stacktrace=format_stacktrace(stacktrace),\n                alert_text=value.get('data'),\n            )\n>       raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\nE       selenium.common.exceptions.StaleElementReferenceException: Message: The previously found element \"\"chevron-down\" Image\" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(\nE           Image, {{134.7, 201.0}, {20.0, 20.0}}, label: 'chevron-down'\nE       )}; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       StaleElementReferenceError: The previously found element \"\"chevron-down\" Image\" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(\nE           Image, {{134.7, 201.0}, {20.0, 20.0}}, label: 'chevron-down'\nE       )}\nE           at errorFromW3CJsonCode (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)\nE           at ProxyRequestError.getActualError (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)\nE           at JWProxy.proxyReqRes (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:410:58)\nE           at processTicksAndRejections (node:internal/process/task_queues:105:5)\n\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/appium/webdriver/errorhandler.py:125: StaleElementReferenceException","steps":[],"attachments":[{"uid":"d5d4f82a163a612","name":"stdout","source":"d5d4f82a163a612.txt","type":"text/plain","size":39}],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":1,"attachmentStep":false,"stepsCount":0,"hasContent":true},"afterStages":[{"name":"driver::0","time":{"start":1728656043941,"stop":1728656045064,"duration":1123},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"appium_server::0","time":{"start":1728656329396,"stop":1728656329412,"duration":16},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false}],"labels":[{"name":"parentSuite","value":"test_case"},{"name":"suite","value":"test_balance_wallete_scenario_"},{"name":"subSuite","value":"TestScenario"},{"name":"host","value":"gimgitaeui-MacBookPro.local"},{"name":"thread","value":"5170-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_case.test_balance_wallete_scenario_"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"f48c06e43cbae386","status":"broken","statusDetails":"selenium.common.exceptions.StaleElementReferenceException: Message: The previously found element \"\"chevron-down\" Image\" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(\n    Image, {{134.7, 201.0}, {20.0, 20.0}}, label: 'chevron-down'\n)}; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\nStaleElementReferenceError: The previously found element \"\"chevron-down\" Image\" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(\n    Image, {{134.7, 201.0}, {20.0, 20.0}}, label: 'chevron-down'\n)}\n    at errorFromW3CJsonCode (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)\n    at ProxyRequestError.getActualError (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)\n    at JWProxy.proxyReqRes (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:410:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","time":{"start":1728655611765,"stop":1728655616250,"duration":4485}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"d6847f380a590f14.json","parameterValues":[]}