{"uid":"8c2e1287a677cded","name":"test_market_trade_normal","fullName":"test_case.test_mandatory_scenarios.TestScenario#test_market_trade_normal","historyId":"b3db562619fcde9316022223a1583361","time":{"start":1728662483632,"stop":1728662959306,"duration":475674},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded\n    at JWProxy.command (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:350:13)\n    at runNextTicks (node:internal/process/task_queues:65:5)\n    at listOnTimeout (node:internal/timers:555:9)\n    at processTimers (node:internal/timers:529:7)\n    at XCUITestDriver.proxyCommand (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)\n    at XCUITestDriver.mobileGetSource (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:50:35)\n    at XCUITestDriver.executeMethod (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:36:12)\n    at XCUITestDriver.execute (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:118:14)","statusTrace":"self = <test_mandatory_scenarios.TestScenario object at 0x106b9d760>\n\n    def test_market_trade_normal(self):\n        self.market_page.click_market_button()\n        self.market_page.swipe_to_title(\"High volume\")\n        self.market_page.click_see_all_button(\"High volume\")\n        time.sleep(3)\n    \n>       assert self.market_page.is_valid_coin_information(), \"코인 데이터 유효성 검사\"\n\ntest_case/test_mandatory_scenarios.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage/market_page.py:109: in is_valid_coin_information\n    is_valid = self.validata_coin_data(coin_data)\npage/market_page.py:140: in validata_coin_data\n    patterns = self.common_page.get_text_by_keyword(\"코인리스트정보\")\npage/common_page.py:82: in get_text_by_keyword\n    return self.regex_utility.get_text_by_keyword(keyword, page_source)\npage/regex_utility.py:46: in get_text_by_keyword\n    return self.get_expressions(keyword, page_source)\npage/regex_utility.py:51: in get_expressions\n    current_page_source = page_source if page_source else self.execute_method.get_page_source_in_json()\npage/execute_method.py:63: in get_page_source_in_json\n    return self.driver.execute_script(\"mobile: source\", {\"format\": \"json\", \"recursive\": True})\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:414: in execute_script\n    return self.execute(command, {\"script\": script, \"args\": converted_args})[\"value\"]\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x109001b50>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"An unknown server-side error occurred while pro...CUITestDriver.execute (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:118:14)\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"\n        https://www.w3.org/TR/webdriver/#errors\n        \"\"\"\n        payload = response.get('value', '')\n        if isinstance(payload, dict):\n            payload_dict = payload\n        else:\n            try:\n                payload_dict = json.loads(payload)\n            except (json.JSONDecodeError, TypeError):\n                return\n            if not isinstance(payload_dict, dict):\n                return\n        value = payload_dict.get('value')\n        if not isinstance(value, dict):\n            return\n        error = value.get('error')\n        if not error:\n            return\n    \n        message = value.get('message', error)\n        stacktrace = value.get('stacktrace', '')\n        # In theory, we should also be checking HTTP status codes.\n        # Java client, for example, prints a warning if the actual `error`\n        # value does not match to the response's HTTP status code.\n        exception_class: Type[sel_exceptions.WebDriverException] = ERROR_TO_EXC_MAPPING.get(\n            error, sel_exceptions.WebDriverException\n        )\n        if exception_class is sel_exceptions.WebDriverException and message:\n            if message == 'No such context found.':\n                exception_class = appium_exceptions.NoSuchContextException\n            elif message == 'That command could not be executed in the current context.':\n                exception_class = appium_exceptions.InvalidSwitchToTargetException\n    \n        if exception_class is sel_exceptions.UnexpectedAlertPresentException:\n            raise sel_exceptions.UnexpectedAlertPresentException(\n                msg=message,\n                stacktrace=format_stacktrace(stacktrace),\n                alert_text=value.get('data'),\n            )\n>       raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\nE       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded\nE       Stacktrace:\nE       UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded\nE           at JWProxy.command (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:350:13)\nE           at runNextTicks (node:internal/process/task_queues:65:5)\nE           at listOnTimeout (node:internal/timers:555:9)\nE           at processTimers (node:internal/timers:529:7)\nE           at XCUITestDriver.proxyCommand (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)\nE           at XCUITestDriver.mobileGetSource (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:50:35)\nE           at XCUITestDriver.executeMethod (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:36:12)\nE           at XCUITestDriver.execute (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:118:14)\n\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/appium/webdriver/errorhandler.py:125: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"rp_logger","time":{"start":1728662278849,"stop":1728662278849,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"appium_server","time":{"start":1728662278849,"stop":1728662289879,"duration":11030},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"os_type","time":{"start":1728662278849,"stop":1728662278849,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1728662481737,"stop":1728662483165,"duration":1428},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"setup","time":{"start":1728662483166,"stop":1728662483631,"duration":465},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded\n    at JWProxy.command (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:350:13)\n    at runNextTicks (node:internal/process/task_queues:65:5)\n    at listOnTimeout (node:internal/timers:555:9)\n    at processTimers (node:internal/timers:529:7)\n    at XCUITestDriver.proxyCommand (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)\n    at XCUITestDriver.mobileGetSource (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:50:35)\n    at XCUITestDriver.executeMethod (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:36:12)\n    at XCUITestDriver.execute (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:118:14)","statusTrace":"self = <test_mandatory_scenarios.TestScenario object at 0x106b9d760>\n\n    def test_market_trade_normal(self):\n        self.market_page.click_market_button()\n        self.market_page.swipe_to_title(\"High volume\")\n        self.market_page.click_see_all_button(\"High volume\")\n        time.sleep(3)\n    \n>       assert self.market_page.is_valid_coin_information(), \"코인 데이터 유효성 검사\"\n\ntest_case/test_mandatory_scenarios.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage/market_page.py:109: in is_valid_coin_information\n    is_valid = self.validata_coin_data(coin_data)\npage/market_page.py:140: in validata_coin_data\n    patterns = self.common_page.get_text_by_keyword(\"코인리스트정보\")\npage/common_page.py:82: in get_text_by_keyword\n    return self.regex_utility.get_text_by_keyword(keyword, page_source)\npage/regex_utility.py:46: in get_text_by_keyword\n    return self.get_expressions(keyword, page_source)\npage/regex_utility.py:51: in get_expressions\n    current_page_source = page_source if page_source else self.execute_method.get_page_source_in_json()\npage/execute_method.py:63: in get_page_source_in_json\n    return self.driver.execute_script(\"mobile: source\", {\"format\": \"json\", \"recursive\": True})\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:414: in execute_script\n    return self.execute(command, {\"script\": script, \"args\": converted_args})[\"value\"]\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x109001b50>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"An unknown server-side error occurred while pro...CUITestDriver.execute (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:118:14)\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"\n        https://www.w3.org/TR/webdriver/#errors\n        \"\"\"\n        payload = response.get('value', '')\n        if isinstance(payload, dict):\n            payload_dict = payload\n        else:\n            try:\n                payload_dict = json.loads(payload)\n            except (json.JSONDecodeError, TypeError):\n                return\n            if not isinstance(payload_dict, dict):\n                return\n        value = payload_dict.get('value')\n        if not isinstance(value, dict):\n            return\n        error = value.get('error')\n        if not error:\n            return\n    \n        message = value.get('message', error)\n        stacktrace = value.get('stacktrace', '')\n        # In theory, we should also be checking HTTP status codes.\n        # Java client, for example, prints a warning if the actual `error`\n        # value does not match to the response's HTTP status code.\n        exception_class: Type[sel_exceptions.WebDriverException] = ERROR_TO_EXC_MAPPING.get(\n            error, sel_exceptions.WebDriverException\n        )\n        if exception_class is sel_exceptions.WebDriverException and message:\n            if message == 'No such context found.':\n                exception_class = appium_exceptions.NoSuchContextException\n            elif message == 'That command could not be executed in the current context.':\n                exception_class = appium_exceptions.InvalidSwitchToTargetException\n    \n        if exception_class is sel_exceptions.UnexpectedAlertPresentException:\n            raise sel_exceptions.UnexpectedAlertPresentException(\n                msg=message,\n                stacktrace=format_stacktrace(stacktrace),\n                alert_text=value.get('data'),\n            )\n>       raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\nE       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded\nE       Stacktrace:\nE       UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded\nE           at JWProxy.command (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:350:13)\nE           at runNextTicks (node:internal/process/task_queues:65:5)\nE           at listOnTimeout (node:internal/timers:555:9)\nE           at processTimers (node:internal/timers:529:7)\nE           at XCUITestDriver.proxyCommand (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)\nE           at XCUITestDriver.mobileGetSource (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:50:35)\nE           at XCUITestDriver.executeMethod (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:36:12)\nE           at XCUITestDriver.execute (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:118:14)\n\n../.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/appium/webdriver/errorhandler.py:125: WebDriverException","steps":[],"attachments":[{"uid":"35a3e5c5404da852","name":"log","source":"35a3e5c5404da852.txt","type":"text/plain","size":2779}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"driver::0","time":{"start":1728662959345,"stop":1728662959367,"duration":22},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100\n    at JWProxy.command (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:350:13)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at XCUITestDriver.proxyCommand (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)\n    at XCUITestDriver.mobileTerminateApp (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/app-management.js:134:7)\n    at XCUITestDriver.executeMethod (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:36:12)\n    at XCUITestDriver.execute (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:118:14)\n","statusTrace":"  File \"/Users/kimkitae/.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/kimkitae/.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/kimkitae/assignment/conftest.py\", line 32, in driver\n    execute_method.terminate_app()\n  File \"/Users/kimkitae/assignment/page/execute_method.py\", line 30, in terminate_app\n    self.driver.execute_script(\"mobile: terminateApp\", {\"bundleId\": \"com.aqx.prex\"})\n  File \"/Users/kimkitae/.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 414, in execute_script\n    return self.execute(command, {\"script\": script, \"args\": converted_args})[\"value\"]\n  File \"/Users/kimkitae/.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/kimkitae/.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/appium/webdriver/errorhandler.py\", line 125, in check_response\n    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"appium_server::0","time":{"start":1728662972771,"stop":1728662972771,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"test_case"},{"name":"suite","value":"test_mandatory_scenarios"},{"name":"subSuite","value":"TestScenario"},{"name":"host","value":"gimgitaeui-MacBookPro.local"},{"name":"thread","value":"16495-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_case.test_mandatory_scenarios"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"8c2e1287a677cded.json","parameterValues":[]}